# Generated by Django 3.2.12 on 2022-03-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asnnumber', models.IntegerField()),
                ('gsdb', models.CharField(max_length=5)),
                ('supplier', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
                ('pknumber', models.IntegerField()),
            ],
        ),
    ]
